version: '3.9'

volumes:
  oracle_volume:

services:
  sao_svelte:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: sao_svelte
    ports:
      - '5173:3000'
    volumes:
      - .:/svelte
      - /svelte/node_modules
    environment:
      DB: ${DB}
      DBUSER: ${DBUSER}
      DBUSERPASS: ${DBUSERPASS}
      JWTSECRETKEY: ${JWTSECRETKEY}
      ORIGIN: ${ORIGIN}
  sao_oracle:
    container_name: sao_oracle
    ports:
      - '1521:1521'
    environment:
      ORACLE_PASSWORD: ${DBPASS}
      APP_USER: ${DBUSER}
      APP_USER_PASSWORD: ${DBUSERPASS}
    volumes:
      - oracle_volume:/opt/oracle/oradata
    image: gvenzl/oracle-xe
